<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="OrangeHRM" duration-ms="71337" started-at="2018-07-28T04:42:47Z" finished-at="2018-07-28T04:43:59Z">
    <groups>
    </groups>
    <test name="pim" duration-ms="58494" started-at="2018-07-28T04:42:47Z" finished-at="2018-07-28T04:43:46Z">
      <class name="com.orangehrm.tests.AddEmployeeTest">
        <test-method status="PASS" signature="openApp(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="openApp" is-config="true" duration-ms="5634" started-at="2018-07-28T10:12:47Z" finished-at="2018-07-28T10:12:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.orangehrm.tests.AddEmployeeTest.verifyAddEmployee() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@2e3967ea]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="login" is-config="true" duration-ms="4491" started-at="2018-07-28T10:12:53Z" depends-on-methods="com.orangehrm.tests.BaseTest.openApp" finished-at="2018-07-28T10:12:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="verifyAddEmployee()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="verifyAddEmployee" duration-ms="18705" started-at="2018-07-28T10:12:57Z" finished-at="2018-07-28T10:13:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual empId: [0324] is not matching with Expected EmpId: [0347] expected [0347] but found [0324]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual empId: [0324] is not matching with Expected EmpId: [0347] expected [0347] but found [0324]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.orangehrm.tests.AddEmployeeTest.verifyAddEmployee(AddEmployeeTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddEmployee -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="closeBrowser" is-config="true" duration-ms="217" started-at="2018-07-28T10:13:16Z" finished-at="2018-07-28T10:13:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="logout" is-config="true" duration-ms="132" started-at="2018-07-28T10:13:16Z" depends-on-methods="com.orangehrm.tests.BaseTest.closeBrowser" finished-at="2018-07-28T10:13:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="openApp(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="openApp" is-config="true" duration-ms="5622" started-at="2018-07-28T10:13:16Z" finished-at="2018-07-28T10:13:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.orangehrm.tests.AddEmployeeTest.verifyAddEmployee1() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@2e3967ea]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="login" is-config="true" duration-ms="4171" started-at="2018-07-28T10:13:22Z" depends-on-methods="com.orangehrm.tests.BaseTest.openApp" finished-at="2018-07-28T10:13:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="verifyAddEmployee1()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="verifyAddEmployee1" duration-ms="17445" started-at="2018-07-28T10:13:26Z" finished-at="2018-07-28T10:13:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual empId: [0324] is not matching with Expected EmpId: [0349] expected [0349] but found [0324]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual empId: [0324] is not matching with Expected EmpId: [0349] expected [0349] but found [0324]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.orangehrm.tests.AddEmployeeTest.verifyAddEmployee1(AddEmployeeTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddEmployee1 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="closeBrowser" is-config="true" duration-ms="2040" started-at="2018-07-28T10:13:44Z" finished-at="2018-07-28T10:13:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@5d76b067]" name="logout" is-config="true" duration-ms="24" started-at="2018-07-28T10:13:46Z" depends-on-methods="com.orangehrm.tests.BaseTest.closeBrowser" finished-at="2018-07-28T10:13:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.orangehrm.tests.AddEmployeeTest -->
    </test> <!-- pim -->
    <test name="Admin" duration-ms="71337" started-at="2018-07-28T04:42:47Z" finished-at="2018-07-28T04:43:59Z">
      <class name="com.orangehrm.tests.AddEmployeeTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="initialize" is-config="true" duration-ms="670" started-at="2018-07-28T10:12:47Z" finished-at="2018-07-28T10:12:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="openApp(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="openApp" is-config="true" duration-ms="8769" started-at="2018-07-28T10:12:47Z" finished-at="2018-07-28T10:12:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.orangehrm.tests.AddEmployeeTest.verifyAddEmployee() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5d534f5d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="login" is-config="true" duration-ms="4496" started-at="2018-07-28T10:12:56Z" depends-on-methods="com.orangehrm.tests.BaseTest.openApp" finished-at="2018-07-28T10:13:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="verifyAddEmployee()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="verifyAddEmployee" duration-ms="19681" started-at="2018-07-28T10:13:00Z" finished-at="2018-07-28T10:13:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual empId: [0324] is not matching with Expected EmpId: [0348] expected [0348] but found [0324]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual empId: [0324] is not matching with Expected EmpId: [0348] expected [0348] but found [0324]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.orangehrm.tests.AddEmployeeTest.verifyAddEmployee(AddEmployeeTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddEmployee -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="closeBrowser" is-config="true" duration-ms="7" started-at="2018-07-28T10:13:20Z" finished-at="2018-07-28T10:13:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="logout" is-config="true" duration-ms="4168" started-at="2018-07-28T10:13:20Z" depends-on-methods="com.orangehrm.tests.BaseTest.closeBrowser" finished-at="2018-07-28T10:13:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="openApp(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="openApp" is-config="true" duration-ms="6911" started-at="2018-07-28T10:13:24Z" finished-at="2018-07-28T10:13:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.orangehrm.tests.AddEmployeeTest.verifyAddEmployee1() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5d534f5d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="login" is-config="true" duration-ms="3965" started-at="2018-07-28T10:13:31Z" depends-on-methods="com.orangehrm.tests.BaseTest.openApp" finished-at="2018-07-28T10:13:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="verifyAddEmployee1()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="verifyAddEmployee1" duration-ms="19245" started-at="2018-07-28T10:13:35Z" finished-at="2018-07-28T10:13:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual empId: [0324] is not matching with Expected EmpId: [0350] expected [0350] but found [0324]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual empId: [0324] is not matching with Expected EmpId: [0350] expected [0350] but found [0324]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.orangehrm.tests.AddEmployeeTest.verifyAddEmployee1(AddEmployeeTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddEmployee1 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="closeBrowser" is-config="true" duration-ms="6" started-at="2018-07-28T10:13:54Z" finished-at="2018-07-28T10:13:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.orangehrm.tests.AddEmployeeTest@394e1a0f]" name="logout" is-config="true" duration-ms="4076" started-at="2018-07-28T10:13:54Z" depends-on-methods="com.orangehrm.tests.BaseTest.closeBrowser" finished-at="2018-07-28T10:13:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.orangehrm.tests.AddEmployeeTest -->
    </test> <!-- Admin -->
  </suite> <!-- OrangeHRM -->
</testng-results>
